### ISSUE TITLE
Module names are incorrect

### ISSUE THREAD

**Issue by JohnPCarvalho** [matheusfiorin/ewbscp#7]
## Why?

The convention for module names in Elixir projects is as follows:

`ApplicationName.Context.ModuleName`

A practical example thinking about our application is for instance the module `WikipediaHandler`
It's location is: `lib/application/workflow/cli/wikipedia_handler.ex`, so, a correct module name would be:

`Ewbscp.Application.Workflow.Cli.WikipediaHandler`

This is not urgent, but it would be nice to have the modules named correctly.

**Comment by matheusfiorin** [comment]
This [PR](https://github.com/matheusfiorin/ewbscp/pull/10) should solve that when merged.

**Comment by JohnPCarvalho** [comment]
I'm closing this guy because we are already implementing this on the #10. I will link this issue there.
